{{- with $.Values.secret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "devops.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{ . | toYaml | nindent 4 }}
  template:
    metadata:
      name: {{ include "devops.fullname" $ }}
      namespace: {{ $.Release.Namespace }}
    type: Opaque
status: {}
{{- end }}
